void vrSetCameraMtx(float matrix[4][4]);
void vrGetHMDMovementDiff(float coord[3]);
void vrGetHMDRotationDiff(float coord[3]);
bool vrGetLeftControllerMatrix(float matrix[4][4]);
bool vrGetRightControllerMatrix(float matrix[4][4]);
void vrGetHMDPosition(float coord[3]);
void vrGetHMDRotation(float coord[3]);
void vrGetHMDMatrix(float matrix[4][4]);
void vrGetHMDMatrixInverted(float matrix[4][4]);
void vrGetHMDTotalPositionChange(float coord[3]);
float vrGetWorldScaleFactor();
float vrGetControllerWorldScaleFactor();
float vrGetUserRealHeight();
bool vrUserHeightIsValid();
